clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "



while :
do

  python3 /home/ubuntu/Desktop/crypticrypto/BTC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ETH1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/USDT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BNB1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XRP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BUSD1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ADA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DOGE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MATIC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SOL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DOT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SHIB1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LTC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TRX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AVAX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/UNI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/WBTC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ATOM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LINK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ETC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XMR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BCH1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/APT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LDO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XLM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/HBAR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FIL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/NEAR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/APE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ALGO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/VET1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/QNT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ICP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GRT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FTM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MANA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AAVE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/EOS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/EGLD1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AXS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FLOW1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/THETA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SAND1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XTZ1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LUNC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/IMX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MINA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CHZ1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/RPL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CRV1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FXS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DASH1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ZEC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MKR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BTTC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CAKE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/KLAY1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XEC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GMX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/IOTA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SNX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/NEO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TWT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/OP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/RUNE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LRC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FTT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AGIX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PAXG1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/OSMO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ZIL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BNX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CVX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ROSE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ROSE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/RNDR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ENJ1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BAT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/STX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DYDX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/1INCH1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LUNA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/NEXO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ASTR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CELO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/HOT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/KAVA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MAGIC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/COMP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/RVN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FET1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/WOO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/HNT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DCR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XEM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/T1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TFUEL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SSV1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BAL1.py &
  sleep 10
  python3 /home/ubuntu/Desktop/crypticrypto/BAL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ONE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GALA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/JASMY1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SUSHI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ENS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/USTC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/OCEAN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/KSM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/IOTX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ANKR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/QTUM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GMT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AUDIO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/INJWAVES1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/YFI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MASK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GLMR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LPT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GLM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/JST1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/KDA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BAND1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FLUX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/OMG1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SKL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ICX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ZRX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/HIVE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AMP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ONT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/IOST1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/RSR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SFP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SXP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ZEN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ILV1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/WAXP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BICO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/RLC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CFX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/STORJ1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SYS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DGB1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CKB1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CELR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/VGX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PEOPLE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/STG1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LSK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/UMA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/HOOK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CHR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/KNC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SCRT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ELF1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/HFT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SLP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PLA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/API31.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PUNDIX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MOB1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/NMR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GAL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XNO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ANT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GTC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SNT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GFT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CVC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/COTI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/POLYX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CTSI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PYR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DUSK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/REQ1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DEXE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ONG1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/STEEM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/HIGH1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ARDR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ALPHA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DENT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/RAD1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PHA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/POWR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SRM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MBOX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PROM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SPELL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/IQ1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/REN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MDX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/WIN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ACH1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XVS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/NKN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/STRAX1.py &
  sleep 10
  python3 /home/ubuntu/Desktop/crypticrypto/STRAX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XRPUP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XRPDOWN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MULTI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LINKUP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LINKDOWN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/HIFI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GBP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/EUR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ETHUP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ETHDOWN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BTCUP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BTCDOWN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BNBUP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BNBDOWN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BETH1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AUD1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ADAP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ADADOWN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/JUV1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/OG1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PERL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ATM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/UFT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CVP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PNT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ACM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MIR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TORN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/OAX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/WABI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AKRO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FOR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PROS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ANC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DREP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AST1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/VIB1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DF1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/WTC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/OOKI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DOCK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AION1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FIDA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/KEY1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FRONT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/EPX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AMB1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CREAM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/VITE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PORTO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/OM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BURGER1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AUTO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/HARD1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/WING1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FARM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PSG1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ADX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TROY1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/COS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CITY1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SANTOS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/QLS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/POLS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ALPACA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PHB1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SNM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TRU1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PERP1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/WAN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LTO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DEGO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AUCTION1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BOND1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BIFI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/KMD1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ALPINE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TOMO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ALCX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/IDEX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DIA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/REI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LEVER1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FIS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LINA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MDT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AGLD1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/QI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/VIDT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AVA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ERN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BTS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/KP3R1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CLV1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CHESS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ORN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BLZ1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/VOXEL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/PIVX1.py &
  sleep 10
  python3 /home/ubuntu/Desktop/crypticrypto/PIVX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GAS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FIRO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/NEBL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BAR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DATA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/QUICK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LAZIO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BEL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/UNFI1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/IRIS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/NULS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TRB1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FIO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/POND1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/JOE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/VTHO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ACA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BSW1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FUN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ALICE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TLM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CTK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/WRX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/OGN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/REEF1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BNT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DAR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/QKC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MTL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/OXT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/STMX1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/DODO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BETA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ATA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/C981.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ARK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FORTH1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/RIF1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/YGG1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LOOM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/UTK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/AERGO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MBL1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SUN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BADGER1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/SUPER1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MOVR1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/CTXC1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/RARE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TKO1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/RAY1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/XVG1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LIT1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/COCOS1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/WNXM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/ARPA1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/GHST1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/MLN1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/BAKE1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/YFII1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/TVK1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/FLM1.py &
  python3 /home/ubuntu/Desktop/crypticrypto/LOKA1.py 

clear
done
